### ISSUE TITLE
Can't build example

### ISSUE THREAD

**Issue by anton-dutov** [vladdeSV/scone#1]
Building example from readme failed

DUB version 0.9.24, built on Aug 19 2015
DMD64 D Compiler v2.069.2
Debian 4.3.3-5 (2016-01-04) x86_64 GNU/Linux

	Performing "debug" build using dmd for x86_64.
	scone 0.0.9-pre: building configuration "library"...
	../../../.dub/packages/scone-0.0.9-pre/source/scone/keyboard.d(77,23): Error: template scone.utility.hasFlag cannot deduce function from argument types !()(int, ControlKey), candidates are:
	../../../.dub/packages/scone-0.0.9-pre/source/scone/utility.d(77,6):        scone.utility.hasFlag(Enum)(Enum check, Enum type) if (is(Enum == enum))
	../../../.dub/packages/scone-0.0.9-pre/source/scone/window.d(132,16): Error: undefined identifier 'posix_windowSize'
	../../../.dub/packages/scone-0.0.9-pre/source/scone/layer.d(307,33): Error: cannot implicitly convert expression (sx) of type ulong to int
	../../../.dub/packages/scone-0.0.9-pre/source/scone/layer.d(310,29): Error: cannot implicitly convert expression (sx) of type ulong to int
	../../../.dub/packages/scone-0.0.9-pre/source/scone/window.d(75,9): Error: undefined identifier 'posix_setCursor'
	../../../.dub/packages/scone-0.0.9-pre/source/scone/layer.d(336,13): Error: undefined identifier 'stdout'
	../../../.dub/packages/scone-0.0.9-pre/source/scone/layer.d(206,31): Error: cannot implicitly convert expression (cast(ulong)(this.w() - col) - this.m_border.length * 2LU) of type ulong to int
	../../../.dub/packages/scone-0.0.9-pre/source/scone/layer.d(347,22): Error: template instance scone.layer.Layer.write!(Slot) error instantiating
	../../../.dub/packages/scone-0.0.9-pre/source/scone/layer.d(533,31): Error: cannot implicitly convert expression (layer.z()) of type ulong to int
	../../../.dub/packages/scone-0.0.9-pre/source/scone/layer.d(543,23): Error: undefined identifier 'min'
	../../../.dub/packages/scone-0.0.9-pre/source/scone/layer.d(550,25): Error: undefined identifier 'max', did you mean variable 'm_x'?
	../../../.dub/packages/scone-0.0.9-pre/source/scone/posix/posixterminal.d(13,5): Error: undefined identifier 'writef'
	../../../.dub/packages/scone-0.0.9-pre/source/scone/posix/posixterminal.d(18,11): Error: undefined identifier 'write'
	../../../.dub/packages/scone-0.0.9-pre/source/scone/posix/posixterminal.d(18,32): Error: undefined identifier 'write'
	../../../.dub/packages/scone-0.0.9-pre/source/scone/posix/posixterminal.d(23,12): Error: undefined identifier 'write'
	../../../.dub/packages/scone-0.0.9-pre/source/scone/posix/posixterminal.d(23,32): Error: undefined identifier 'write'
	../../../.dub/packages/scone-0.0.9-pre/source/scone/posix/posixterminal.d(28,5): Error: undefined identifier 'write'
	../../../.dub/packages/scone-0.0.9-pre/source/scone/window.d(89,9): Error: undefined identifier 'posix_title'
	../../../.dub/packages/scone-0.0.9-pre/source/scone/window.d(102,9): Error: undefined identifier 'posix_cursorVisible'
	../../../.dub/packages/scone-0.0.9-pre/source/scone/window.d(116,9): Error: undefined identifier 'posix_lineWrapping'
	dmd failed with exit code 1.

**Comment by vladdeSV** [comment]
Sadly I do not have either access to a linux machine or a 64-bit compiler. I will do my best to fix these issues you currently have.

**Comment by vladdeSV** [comment]
I just updated the library.

Would you like to rebuild it?

**Comment by anton-dutov** [comment]
First try:

	scone ~master: building configuration "library"...
	../../../.dub/packages/scone-master/source/scone/window.d(9,25): Error: module posixterminal is in file 'scone/posixterminal.d' which cannot be read
	import path[0] = ../../../.dub/packages/scone-master/source/
	import path[1] = /usr/include/dmd/phobos
	import path[2] = /usr/include/dmd/druntime/import
	dmd failed with exit code 1.


So i fixed window.d import scone.posixterminal to  scone.posix.posixterminal;

and got

	scone ~master: building configuration "library"...
	../../../.dub/packages/scone-master/source/scone/layer.d(329,26): Error: function scone.window.setCursor (int x, int y) is not callable using argument types (int, ulong)
	../../../.dub/packages/scone-master/source/scone/layer.d(271,30): Error: cannot implicitly convert expression (windowSize()) of type ushort[] to int[]
	../../../.dub/packages/scone-master/source/scone/window.d(89,9): Error: undefined identifier 'posix_title'
	dmd failed with exit code 1.

i think you need install some distributive to virtual machine

**Comment by vladdeSV** [comment]
Thank you for bearing with me. This pre release was only tested on windows, sadly not POSIX

I've updated the repo and I think that should fix your issues. More issues might arise where size_t (ulong on 64bit) is set to an int

**Comment by anton-dutov** [comment]
Now it works.
Also look at https://travis-ci.org/  -  DLang/Dub supported

**Comment by vladdeSV** [comment]
Sadly scone isn't functioning for POSIX yet, no key input :(
