### ISSUE TITLE
Proper logging

### ISSUE THREAD

**Issue by vladdeSV** [vladdeSV/scone#17]
I am uncertain how logging should be implemented (I do not know the *Best Practices*™). Currently, I have commented out pseudo-"logging code", in the form of:

```d
//log(warning, "X might be Y");
```

Any help with implementing **good** logging is very much appreciated 🙏.

**Comment by logicfish** [comment]
Maybe you should use the `debug` constants
```
debug(Something) {
  trace("message");
}
```

**Comment by vladdeSV** [comment]
I'm currently using `std.experimental.logger : sharedLogger`, and aliasing it to just `logger` (7abf2bfe84f63906f46607d1952fbc004f1d0d13).

I'm in the process of replacing/adding logs where I see fit.
