### ISSUE TITLE
progress bar?

### ISSUE THREAD

**Issue by bubnenkoff** [vladdeSV/scone#2]
is it's possible with scone?

**Comment by vladdeSV** [comment]
It certainly is possible. Although there is no built-in support for progressbars, you could implement https://gist.github.com/vladdeSV/802a7215268cfc6bbf72 yourself.

Simply update a label with the string returned from gistfile above.

**Comment by vladdeSV** [comment]
If you feel this has been resolved, feel free to close this issue :smile:

**Comment by bubnenkoff** [comment]
Thanks for link, but it's look like it's need some external code (probably API calls) to get terminal width.

**Comment by vladdeSV** [comment]
You can get the console size with https://github.com/vladdeSV/scone/blob/master/source/scone/window.d#L57

**Comment by bubnenkoff** [comment]
Could you explain how this function works?
```
auto windowSize() @property
{
    int[2] ret;
    version(Windows) ret = win_windowSize;
    return ret;
}
```

It's do not like winapi. What is it? What about posix?

**Comment by vladdeSV** [comment]
Sadly scone is not cross platform, and only works for Windows.

The function calls the windows api and returns the size as an `int[2]`

**Comment by bubnenkoff** [comment]
Could you show what WinApi function it's calling? Just for better
understanding of code.

2016-09-14 13:02 GMT+03:00 Vladde Nordholm <notifications@github.com>:

**Comment by rjmcguire** [comment]
For unix with termios: http://man7.org/linux/man-pages/man4/tty_ioctl.4.html

On Wed, Sep 14, 2016 at 12:05 PM, Dmitry Bubnenkov <notifications@github.com

**Comment by vladdeSV** [comment]
Once upon a time there was partial support for POSIX, however, due to problems with input, I scrapped it. The code used for terminal size was https://github.com/vladdeSV/scone/blob/old-posix/source/scone/posix/posix_terminal.d#L45

@bubnenkoff If you follow the function, you end up at https://github.com/vladdeSV/scone/blob/master/source/scone/windows/win_console.d#L77

**Comment by vladdeSV** [comment]
The issue at hand seems to be the lack of POSIX support. Sadly there are no plans to support POSIX.

Progressbars are not built-in, but can be manually constructed. If you feel the issue is solved, feel free to close it 👍

**Comment by vladdeSV** [comment]
I added progress bars, available in the next release
