### ISSUE TITLE
Just got the following error  @ scone-2.1.0/scone/source/scone/os/posix.d(162,23)

### ISSUE THREAD

**Issue by EmTee70** [vladdeSV/scone#28]
dmd-2.083.0)mt@dlang-pad-110-15IBR:~/d-learn/moon-fruit$ dub --compiler=dmd
Performing "debug" build using dmd for x86_64.
scone 2.1.0: building configuration "library"...
moon-fruit ~master: building configuration "application"...
../../.dub/packages/scone-2.1.0/scone/source/scone/os/posix.d(162,23): Error: undefined identifier eventsFromSequence, did you mean function eventFromSequence?
dmd failed with exit code 1.

I just tried to update my old program to work with latest version of scone.
p.s. It is not so important for me, but want to report this to you.

Regrads mt.

**Comment by vladdeSV** [comment]
Hello.

Can you verify you have the following functions in `scone/input/input_event.d`

* `on line 211: InputEvent eventFromSequence(InputSequence sequence)`
* `on line 226: InputEvent[] eventsFromSequence(uint[] sequence)`

**Comment by EmTee70** [comment]
Code from 210-230, the function is there but not found?
I don't know why.

```
 /// Get InputEvent from sequence
    /+ todo: remove the comment signs | package(scone)+/ InputEvent eventFromSequence(InputSequence sequence)
    {
        // check for input sequence in map
        if((sequence in _inputEvents) !is null)
        {
            return _inputEvents[sequence];
        }

        // if not found, return unknown input
        auto unknownInputEvent = InputEvent(SK.unknown, SCK.none, false);
        unknownInputEvent._keySequences = sequence;
        return unknownInputEvent;
    }
From 210 to 232, 
    /// TODO: this should check for multiple keypresses, according to Github issue #13
    /+ todo: remove the comment signs |package(scone)+/ InputEvent[] eventsFromSequence(uint[] sequence)
    {
        // todo: here should code go to check if an input exists. this fix is of version type PATCH
        auto inputEvents = [eventFromSequence(InputSequence(sequence))];

        return inputEvents;
    }
```

**Comment by vladdeSV** [comment]
I cannot reproduce this. Could you clean you dub folders, in case some cached version is being used?

**Comment by EmTee70** [comment]
There was an old input.d inside my src....:-(
Problem solved! Sorry for that!
