### ISSUE TITLE
Setting the text of a UITextInput to an empty string causes a RangeError

### ISSUE THREAD

**Issue by DanSze** [vladdeSV/scone#3]
Pretty much what it says on the tin. Because the cursor position is never updated after changing the text of the UITextInput to an empty string, when it tries to insert the cursor into the string for rendering it goes out of bounds given the cursor wasn't at 0.

I've tried the obvious patch of overriding the property, but the compiler doesn't like mixing type inference and overriding, so that doesn't work.

**Comment by vladdeSV** [comment]
Thank you for the feedback! Will look at it asap 👍🏼

**Comment by vladdeSV** [comment]
I will approach this issue tomorrow, stressful day today 😢  @DanSze

**Comment by vladdeSV** [comment]
Pushed a fix, please tell me if it fixes your problem :smile: @DanSze

**Comment by vladdeSV** [comment]
@DanSze If the issue is resolved, feel free to close this issue

**Comment by DanSze** [comment]
Sorry for the delay, I haven't had time to work on any side projects what with midterms around the corner.

Setting text works, but the new text property shadows the inherited ones, making reading text without then setting it impossible.

**Comment by vladdeSV** [comment]
Sorry, did not understand what you meant. Could you please rephrase the issue at hand?

**Comment by DanSze** [comment]
Currently, when you have some text field, and you try to read the text property, you get a compile time error like `Error: function scone.console.ui.selectable.text_input.UITextInput.text (string text) is not callable using argument types ()`

By default, any method will shadow any other methods with the same name in a superclass, even if it overrides one of them. If I recall correctly, the intended way to go about fixing this was to include something like
```
alias <method> = super.<method>
```

I would submit a pull request, but exam week is still eating up any time I have for side projects.

**Comment by vladdeSV** [comment]
If I understood you correctly, then I am happy to inform you that your issue is fixed as of now

![gif](http://i.imgur.com/k9hpPta.gif)

**Comment by DanSze** [comment]
Sweet! Looks like everything works now.
