### ISSUE TITLE
How to properly interact with InputEvent?

### ISSUE THREAD

**Issue by deviator** [vladdeSV/scone#30]
I want to build interface with user input. Input must be a strings (command names) for example `help` or `exit`. But I don't find methods to manipulate with `InputEvent` properly (backspace, delete, up/down for history etc). Is they methods are exists? Maybe in other companion project?

**Comment by vladdeSV** [comment]
Unfortunately, no. There are no built-in functions to manipulate input as you described.

The best I can recommend you would be to salvage functionality from scone's [now removed "UI library"](https://github.com/vladdeSV/scone/blob/41b14ebe565352e169adc1a34af42915dd1a2bbf/source/scone/console/ui/selectable/text_input.d) (from version 1 of scone, over two years old)
