### ISSUE TITLE
Not printable char

### ISSUE THREAD

**Issue by EmTee70** [vladdeSV/scone#7]
Hi, when doing a loop with randomized printing of 100 chars on the window with one window.print() at the end. I get some unprintable chars displayed as [??] on the window.
When calling window.print() after every char, no unprintable [??] chars appear.

**Comment by vladdeSV** [comment]
Could you provide the code you used?

**Comment by vladdeSV** [comment]
Also, please provide version (eg master, 1.2, 2.0-pre) and OS

**Comment by EmTee70** [comment]
yes, sure: 2.0-pre on Ubuntu 14.04 LTS in XFCE Terminal and 

`import scone;
import std.random:uniform;


        enum width = 40;
        enum height = 20;
        int xpos = width/2;
        int ypos = height/2;
        int[height][width] mirror;
        
        void place_random(int num, wchar zeichen, Color fore_ground = Color.red, int value = 0){
                for(auto j=0;j<num; j++){
                   auto rx = uniform(0,width);
                   auto ry = uniform(0,height);
                   window.write(rx,ry,fg(fore_ground),bg(Color.black),zeichen);
                   mirror[rx][ry]=value;
                   window.print();
}
void main()
{

        window.resize(width,height);
        window.clear();

        for(auto x=0; x<width;x++){
           for(auto y=0;y<height;y++){
              window.write(x,y,bg(Color.black)," ");
           }
        }
        window.print();
        place_random(100,'\u2660',fg(Color.red),10);
        place_random(400,'#',fg(Color.white_dark),-1000);
        place_random(100,'\u2663',fg(Color.yellow_dark),20);
}



`

**Comment by vladdeSV** [comment]
I see you use `wchar` in your code, which sadly isn't supported by scone. (I decided this sometime long ago because wchar and the windows console did not go well together).

If you change from `wchar` to `char`, does that "fix" your problem?

**Comment by EmTee70** [comment]
ok, will try. How do I request if for example the 'r' key is pressed? My syntax seams to be wrong.
`input.key == ?? `

**Comment by vladdeSV** [comment]
`input.key == SK.r``SK` stands fo "scone key"Med vänliga hälsningar,Vladimirs NordholmSent from my rymdtelefonOn Jun 27, 2017 13:47, EmTee70 <notifications@github.com> wrote:ok, will try. How do I request if for example the 'r' key is pressed? My syntax seams to be wrong.
input.key == ??

**Comment by EmTee70** [comment]
Now I realized window.getInputs() seams to return nothing.

**Comment by vladdeSV** [comment]
Could you test with master branch?

I have only tested this with Mac/Ubuntu GNOME, so it could be the input not working at all :(

**Comment by EmTee70** [comment]
Looks better!
Seams to work! Thank you!
Other question: Do you know how to speed up keys? I mean when holding a key pressed than it should repeat faster. something with xset -r ...

**Comment by vladdeSV** [comment]
Good to know! 2.0.0-pre.1 only handles a few macOS inputs. master supports almost all macOS/Ubuntu keys.

I'll close this issue, since the initial problem is resolved 😄 

---

I do not believe repeat speed is something **scone** can set, as it is (I think) not handled by the terminal.
