### ISSUE TITLE
naming of colors

### ISSUE THREAD

**Issue by EmTee70** [vladdeSV/scone#8]
The Color.red_dark is brighter than Color.red,
same for blue_dark, white_dark, yellow_dark all brighter than without _dark. Please check.
Regards mt.

**Comment by vladdeSV** [comment]
Could you test again with master branch? I just updated some code 😁

**Comment by EmTee70** [comment]
Hmm, now the colors are wrong, fg(Color.yellow_dark) => light red
and yellow_dark seams to be a different red.

 bg(Color.black) => looks gray now but this is ok, because black_dark is dark!
And white and white_dark are as they should be.

**Comment by vladdeSV** [comment]
Just to be clear, do the colors names result in wrong colors? If I understood it correctly, `fg(Color.yellow_dark)` displayed as light red?

`black`, `black_dark`, `white`, `white_dark` are a bit odd, but that's by design.

**Comment by EmTee70** [comment]
I could evaluate it in more detail, making a screen shot of all colors in a matrix with all possible backgrounds, too. My impression was that the yellow_dark was something but not yellow :-) 

But now I am not using it ... I am doing a little game I originally wrote 198x  x < 5 for C64 with the amazing title moon fruit :-) I am now nearly 47...I can offer it as additional example...

**Comment by vladdeSV** [comment]
Sorry, I did not understand your answer.

Does `Color.yellow_dark` show text as red color?

**Comment by EmTee70** [comment]
#aa5500 is the color of yellow_dark

**Comment by vladdeSV** [comment]
Ah, yes that is colour of yellow dark. Might be a bit confusing, but that is what it looks like.

Thank you for your help 👍
